#!/bin/bash
set -e
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
LOCAL=${SCRIPT_DIR}/current.json
REMOTE=s3://akiimages/mishna/current.json
LOG_FILE=${SCRIPT_DIR}/mishna.log

cd $SCRIPT_DIR
date >> $LOG_FILE

uv run python /home/akiva/projects/mishna/is_yomtov.py /home/akiva/projects/mishna/.env.json || exit 1
/usr/bin/aws s3 cp $REMOTE $LOCAL
uv run python /home/akiva/projects/mishna/get_mishna.py /home/akiva/projects/mishna/.env.json 2>&1 >> $LOG_FILE
/usr/bin/aws s3 cp $LOCAL $REMOTE
echo done >> $LOG_FILE
