[project]
name = "mishna"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.13.2",
    "async-timeout>=5.0.1",
    "attrs>=25.4.0",
    "beautifulsoup4>=4.14.3",
    "certifi>=2025.11.12",
    "chardet>=5.2.0",
    "idna>=3.11",
    "multidict>=6.7.0",
    "requests>=2.32.5",
    "soupsieve>=2.8.1",
    "telepot>=12.7",
    "typing-extensions>=4.15.0",
    "urllib3>=2.6.2",
    "yarl>=1.22.0",
]
