#!/bin/bash
set -e
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
LOCAL=${SCRIPT_DIR}/current.json
REMOTE=s3://akiimages/mishna/current.json
LOG_FILE=${SCRIPT_DIR}/mishna.log

/usr/bin/aws s3 cp $LOCAL $REMOTE
